<%@ Page Title="Facturas" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="WebFormsFacturas.Facturas.Index" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>


    <asp:Button runat="server" ID="BtnCreate" CssClass="btn btn-primary" Text="Agregar Nuevo" OnClick="BtnCreate_Click" />

    <asp:GridView runat="server"
        ID="GridView1"
        CssClass="table table-condensed"
        EmptyDataText="No se encuentran facturas"
        OnRowEditing="GridView1_RowEditing"
        OnRowDeleting="GridView1_RowDeleting"
        AutoGenerateColumns="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true">
        <Columns>
            <asp:TemplateField HeaderText="ID" Visible="false">
                <ItemTemplate>
                    <asp:Label ID="lbl_ID" runat="server" Text='<%#Eval("ID") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
